### ISSUE TITLE
plasma-systemmonitor - processes missing a few services icons

### ISSUE THREAD

**Issue by buufmax** [SylEleuth/gruvbox-plus-icon-pack#109]
Run on Konsole
`plasma-systemmonitor --page-name=Processes`

Many apps won't show icons while some others do.

As a KDE user, i use often this place from plasma-systemmonitor, which is why i'm wondering can be filled with icons those services?

**Comment by buufmax** [comment]
This [package](https://store.kde.org/p/1990795) cover all services without icons with a generic icon.

I did a quick check and found out his "preferences-system.svg" on apps/64 enabling those missing icons if i'm not wrong.

Your gruvbox-plus also have preferences-system, but don't have a 64 size on apps.

**Comment by SylEleuth** [comment]
I've just installed that icons pack and don't see any changes. Can You show me how it looks on Your side?

**Comment by buufmax** [comment]
gruvbox-plus
![Screenshot_20241201_214322](https://github.com/user-attachments/assets/cc17ad1d-b653-43c0-9395-153852daac23)
Uos
![Screenshot_20241201_214356](https://github.com/user-attachments/assets/344277eb-b2e0-4a59-8045-59b1ffbf3f6f)

When i did renamed his "preferences-system.svg" the generic icons blue+white disappeared. That's why i suspected to that name, but i'm not sure.

**Comment by SylEleuth** [comment]
You are right. It's that icon, and it's not, because it's already in the pack. It's `.svg` (symlink to `preferences-system`). Yes, only that. It looks like if there is no icon available it will use something that has no name. I believe it's just an error because You can't have "empty" file name (it happened to me few times - remove a name, and accidentally press enter and there You have it). I will not add it to the pack, but You can use it on Your own now, especially when You know what it is.

**Comment by buufmax** [comment]
Okay, thank you for your clarification and help.
