### ISSUE TITLE
Some icons not rendering in color

### ISSUE THREAD

**Issue by NickHastings** [SylEleuth/gruvbox-plus-icon-pack#20]
On my system some (all?) of the icons under apps/16, apps/16@2x, apps/22, and apps/22@2x do not render in color. The larger sizes seem ok. Actually reading the contents of the svg files it looks like they should be color. I tested this with a couple of different image viewers that I think use different svg libraries.

Let me know if more information is needed.

**Comment by SylEleuth** [comment]
Apps 16 are monochromatic so there is only one color. If you are talking about the part of code with "colors" it's a relic of the Suru++ pack or even different one and it will be removed. It's not priority at the moment.
If You don't like it and prefer to use scalable (colorful) icons everywhere You could make 16 folder a symlink to scalable or remove it entirely. It will break some parts of the system, e.g. in KDE some option icons will be still monochromatic because they are located in devices folder.

**Comment by NickHastings** [comment]
Thanks for the info. Think I'll just run a branch that with those monochromatic icons removed.
