### ISSUE TITLE
Icons with spaces in file names generate an invalid icon cache

### ISSUE THREAD

**Issue by varris1** [SylEleuth/gruvbox-plus-icon-pack#27]
Commit: b5f56e3ebdd716931ca92e9ac6be254d30f93995

Having file names with spaces create an invalid icon cache if you use "gtk-update-icon-cache". You can check with the "-v" parameter.

file names affected:

> Gruvbox-Plus-Dark/apps/16/5298_World of Warcraft Launcher.0.svg
> Gruvbox-Plus-Dark/apps/16/56B4_Battle.net Launcher.0.svg
> Gruvbox-Plus-Dark/apps/16/Epic Games Launcher.svg
> Gruvbox-Plus-Dark/apps/scalable/5298_World of Warcraft Launcher.0.svg
> Gruvbox-Plus-Dark/apps/scalable/Epic Games Launcher.svg
> Gruvbox-Plus-Dark/apps/symbolic/5298_World of Warcraft Launcher.0.svg
> Gruvbox-Plus-Dark/apps/symbolic/56B4_Battle.net Launcher.0-symbolic.svg
> Gruvbox-Plus-Dark/apps/symbolic/Epic Games Launcher-symbolic.svg

**Comment by SylEleuth** [comment]
Spaces have to stay because those names are for wine apps and Windows filenames usually contain only one dot just before extension at the end and besides that use spaces (sometimes dashes). Icon cache is generated despite of that and if You have message that says it's invalid, it's just a warning, nothing more, and You can safely ignore it.

I'm not sure how it's related to linked commit.
