### ISSUE TITLE
Icon request: Spotube

### ISSUE THREAD

**Issue by Velho-P** [SylEleuth/gruvbox-plus-icon-pack#42]
Program: Spotube
Site: https://spotube.org/
SVG: https://github.com/KRTirtho/spotube/blob/master/assets/spotube-logo.svg
xprop:
> _NET_FRAME_EXTENTS(CARDINAL) = 0, 0, 0, 0
> _NET_WM_ALLOWED_ACTIONS(ATOM) = _NET_WM_ACTION_CLOSE, _NET_WM_ACTION_ABOVE, _NET_WM_ACTION_BELOW, _NET_WM_ACTION_FULLSCREEN, _NET_WM_ACTION_MOVE, _NET_WM_ACTION_MAXIMIZE_HORZ, _NET_WM_ACTION_MAXIMIZE_VERT, _NET_WM_ACTION_MINIMIZE, _NET_WM_ACTION_CHANGE_DESKTOP, _NET_WM_ACTION_STICK
> WM_STATE(WM_STATE):
> 		window state: Normal
> 		icon window: 0x3fcdb200
> _NET_WM_DESKTOP(CARDINAL) = 0
> _NET_WM_STATE(ATOM) = _NET_WM_STATE_MAXIMIZED_HORZ, _NET_WM_STATE_MAXIMIZED_VERT
> WM_HINTS(WM_HINTS):
> 		Client accepts input or input focus: True
> 		Initial state is Normal State.
> 		window id # of group leader: 0x4600001
> _GTK_THEME_VARIANT(UTF8_STRING) = 
> _MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x2, 0x0, 0x0, 0x0, 0x0
> XdndAware(ATOM) = BITMAP
> _GTK_WINDOW_OBJECT_PATH(UTF8_STRING) = "/org/gtk/Application/anonymous/window/1"
> _GTK_APPLICATION_OBJECT_PATH(UTF8_STRING) = "/org/gtk/Application/anonymous"
> _GTK_UNIQUE_BUS_NAME(UTF8_STRING) = ":1.84"
> _NET_WM_OPAQUE_REGION(CARDINAL) = 
> _NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
> _NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 73400325, 73400326
> _NET_WM_USER_TIME_WINDOW(WINDOW): window id # 0x4600004
> WM_CLIENT_LEADER(WINDOW): window id # 0x4600001
> _NET_WM_PID(CARDINAL) = 4618
> WM_LOCALE_NAME(STRING) = "pt_BR.UTF-8"
> WM_CLIENT_MACHINE(STRING) = "VelhoPC"
> WM_NORMAL_HINTS(WM_SIZE_HINTS):
> 		program specified location: 0, 0
> 		program specified minimum size: 0 by 0
> 		program specified base size: 0 by 0
> 		window gravity: NorthWest
> WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING, _NET_WM_SYNC_REQUEST
> WM_CLASS(STRING) = "spotube", "Spotube"
> WM_ICON_NAME(STRING) = "Spotube"
> _NET_WM_ICON_NAME(UTF8_STRING) = "Spotube"
> WM_NAME(STRING) = "Spotube"
> _NET_WM_NAME(UTF8_STRING) = "Spotube"

I love your work, thank you very much!

**Comment by SylEleuth** [comment]
https://github.com/SylEleuth/gruvbox-plus-icon-pack/commit/d3f8a574a409b035f033ddd2f344addde9961783

Unfortunately **Spotube** author decided to use .png file for icon instead of .svg and soft-coded it into .desktop file. The only way to use the new icon is to copy _spotube.desktop_ file from `/usr/share/applications` directory to `~/.locale/share/applications` and to rename `Icon=/usr/share/icons/spotube/spotube-logo.png` line to simple `Icon=spotube` (or `Spotube`, or `spotube-logo`, I've prepared those options just in case author decide to change it in the future). If You already knew how to do it then I apologise for detailed instructions. I thought I'll write it just in case someone else will have problems with that app and icon.

Thank You and have a nice day.

**Comment by Velho-P** [comment]
Thank you!
Appreciate the instructions, I didn't knew how to do it
