### ISSUE TITLE
In Plasma 6

### ISSUE THREAD

**Issue by thisKnull** [SylEleuth/gruvbox-plus-icon-pack#48]
Plasma 6 & Arch Linux

I have observed that

1.okular cannot be opened
2.Shutdown, reboot, and logout in the start menu are very slow.

All of these do not appear when using the breeze icon.

**Comment by SylEleuth** [comment]
It might be related to https://github.com/SylEleuth/gruvbox-plus-icon-pack/issues/47. It's about rendering icons but I think that plasma 6 crashes whenever have to do with icons that have _blured_ elements. They don't have to be used by system, just displayed. Whenever I open folder with them `dolphin` just closes. I'm working on it right now but it will take some time because there is a lot of icons with blur.

**Comment by SylEleuth** [comment]
I've pushed the fix for the icon related to Okular (https://github.com/SylEleuth/gruvbox-plus-icon-pack/commit/44dc3ab11c2e7a303fd41997de7f6728092a99bb). Could You pull it and check if it opens now?

**Comment by thisKnull** [comment]
Good, okular can open it.

> 2.Shutdown, reboot, and logout in the start menu are very slow.

It's still slow.

**Comment by SylEleuth** [comment]
I understand, working on it. I just needed to verify my theory about problem.
Thank You.

**Comment by SylEleuth** [comment]
It's fixed now. Thank You for Your patience.
