### ISSUE TITLE
can you change the color of different audio file types

### ISSUE THREAD

**Issue by RustoMCSpit** [SylEleuth/gruvbox-plus-icon-pack#49]
https://www.pling.com/p/1012233 has different colored icons for different audio file types and if theyre currently being cut or not

**Comment by SylEleuth** [comment]
I'm not sure about "being cut" thing, but I have plans to overhaul `mimetypes/scalable` and to change colours of the background to differentiate the type. I might even add text at the top just like in compressed files or at the bottom like in documents.

It will have to wait though, because I have other things to do first. Be patient please.
(I really have to add a _Roadmap_ info to the _Readme_).

**Comment by RustoMCSpit** [comment]
can the change colors apply to files? you can do that in the standard linux mint icon pack

**Comment by RustoMCSpit** [comment]
so i can make one file green and another blue

**Comment by SylEleuth** [comment]
Sure You can. There are icons for _mp3_, _ogg_, _aac_, _flac_ and so on. For now they are all linked to one type of mimetype icon (`application-audio.svg`). You would have to create a new one and make a symlink to that one, e.g. _ogg_ has 5 icons in total. Make one of them normal, for example `application-ogg.svg`, and then soft link other 4 to that one.

I'm moving this issue to the discussions.
