### ISSUE TITLE
mpv player - wrong symbolic icon

### ISSUE THREAD

**Issue by genkieagle** [SylEleuth/gruvbox-plus-icon-pack#64]
mpv player have a wrong symbolic icon, instead of a video player displays as an audio player.

To reach on it
KDE Plasma 6 / System Settings / Default Applications / Video Player / mpv Media Player

![Screenshot_20240717_154522](https://github.com/user-attachments/assets/1af8ee2d-1088-42ef-a00f-09cbf4762f88)

We know that mpv player is capable for playing both audio and video, but i think the symbolic icon player should be more suitable for a video player.

![Screenshot_20240717_155102](https://github.com/user-attachments/assets/b1b476f6-18fb-41b6-a1f9-8a9a6edf5221)
Maybe you can use that xt7-player-mpv-symbolic for "mpv-symbolic"?

**Comment by SylEleuth** [comment]
Those icons are ready and are waiting for a review. What I mean is that right now I'm finishing uploading `panel` folder, after that I upload `status` folder, and publish a new release. After that I will start uploading `apps`. I know that many icons are missing, but because I don't want to mess up my git pushes (it's easier for me to organize what to do and when) I will wait with that until then. I should finish those two folders within a week or two. If You are willing to wait I will upload new mpv icons first thing after that, and all video and audio icons next.
